name: Daily Commit Workflow

on:
  schedule:
    # Runs every day at 07:30 UTC
    - cron: '30 7 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "24f2005754@ds.study.iitm.ac.in"

      - name: Create a daily commit for email 24f2005754@ds.study.iitm.ac.in
        run: |
          echo "Daily update $(date)" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit from GitHub Action"
          git push
